// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchedulerMeeting.Api.Data;

namespace SchedulerMeeting.Api.Migrations
{
    [DbContext(typeof(SchedulerMeetingContext))]
    [Migration("20200420122326_AddSeedData")]
    partial class AddSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("SchedulerMeeting.Api.Models.MeetingRoom", b =>
                {
                    b.Property<Guid>("MeetingRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Local")
                        .HasColumnType("TEXT");

                    b.HasKey("MeetingRoomId");

                    b.ToTable("MeetingRooms");

                    b.HasData(
                        new
                        {
                            MeetingRoomId = new Guid("fa53bb0c-b2e3-4d95-8d2f-d2cbf86b0d02"),
                            Active = true,
                            Description = "Meeting Room 1",
                            Local = "Alameda dos Anjos"
                        },
                        new
                        {
                            MeetingRoomId = new Guid("618acd1f-897c-4a30-b0d2-8e8e787f7e94"),
                            Active = true,
                            Description = "Meeting Room 2",
                            Local = "Gotam City"
                        },
                        new
                        {
                            MeetingRoomId = new Guid("620b3555-4526-440b-af3c-3fb5c2aacfa5"),
                            Active = true,
                            Description = "Meeting Room 1",
                            Local = "Konoha"
                        });
                });

            modelBuilder.Entity("SchedulerMeeting.Api.Models.Scheduling", b =>
                {
                    b.Property<Guid>("SchedulingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observation")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RoomMeetingRoomId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SchedulingEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SchedulingStart")
                        .HasColumnType("TEXT");

                    b.HasKey("SchedulingId");

                    b.HasIndex("RoomMeetingRoomId");

                    b.ToTable("Schedulings");
                });

            modelBuilder.Entity("SchedulerMeeting.Api.Models.Scheduling", b =>
                {
                    b.HasOne("SchedulerMeeting.Api.Models.MeetingRoom", "Room")
                        .WithMany()
                        .HasForeignKey("RoomMeetingRoomId");
                });
#pragma warning restore 612, 618
        }
    }
}
